### ISSUE TITLE
Bokeh API change: cursession gone

### ISSUE THREAD

**Issue by MichaelPaddon** [vitruvianscience/OpenDeep#23]
On line 18 of build/lib/opendeep/monitor/plot.py, symbol cursession is imported from bokeh.plotting:

    from bokeh.plotting import (curdoc, cursession, figure, output_server, push, show)

The symbol cursession no longer exists in the latest bokeh version (0.11) available via pip. Work around: install version 0.10.

**Comment by gree2** [comment]
which one to use in version 0.11.0?

**Comment by vitruvianscience** [comment]
Currently fixing the monitor api - for the time being use the older 0.10 version of Bokeh

**Comment by mbeissinger** [comment]
Fixed plotting to work with Bokeh 0.11.x in the 'develop' branch, will merge into master tonight.

**Comment by manugarri** [comment]
Still having this issue with `bokeh==0.11.1`. Is `cursession` not in the api anymore?

**Comment by vitruvianscience** [comment]
I don't see this comment on the GitHub issue anymore - were you able to
resolve it? I believe the latest version of OpenDeep works with the latest
version of Bokeh.
